# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RecordAudio = QtWidgets.QPushButton(self.centralwidget)
        self.RecordAudio.setGeometry(QtCore.QRect(350, 470, 121, 27))
        self.RecordAudio.setObjectName("RecordAudio")
        self.DiscussionHistory = QtWidgets.QTextBrowser(self.centralwidget)
        self.DiscussionHistory.setGeometry(QtCore.QRect(280, 100, 256, 192))
        self.DiscussionHistory.setObjectName("DiscussionHistory")
        self.DiscussionDisplay = QtWidgets.QPushButton(self.centralwidget)
        self.DiscussionDisplay.setGeometry(QtCore.QRect(330, 10, 151, 27))
        self.DiscussionDisplay.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.DiscussionDisplay.setObjectName("DiscussionDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menutest = QtWidgets.QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menutest.menuAction())

        self.retranslateUi(MainWindow)
        self.RecordAudio.clicked['bool'].connect(self.RecordAudio.toggle) # type: ignore
        self.DiscussionDisplay.toggled['bool'].connect(self.DiscussionDisplay.setChecked) # type: ignore
        self.DiscussionDisplay.toggled['bool'].connect(self.DiscussionHistory.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.RecordAudio, self.DiscussionHistory)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RecordAudio.setText(_translate("MainWindow", "Record Audio"))
        self.DiscussionDisplay.setText(_translate("MainWindow", "Display Discussion"))
        self.menutest.setTitle(_translate("MainWindow", "Microphone"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
